version: '3'
services:
  db:
    image: mariadb:latest
    container_name: watcher-db
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: watcher
      MYSQL_USER: admin
      MYSQL_PASSWORD: localdevelopment
      MYSQL_ROOT_PASSWORD: localdevelopment
