apiVersion: v1
kind: Service
metadata:
  name: mozilla-watcher-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: mozilla-watcher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mozilla-watcher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mozilla-watcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: mozilla-watcher
    spec:
      hostname: mozilla-watcher
      containers:
        - name: mozilla-watcher
          image: mozillach/watcher:<TAG>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "300m"
              memory: "300M"
            requests:
              cpu: "80m"
              memory: "80M"
          ports:
            - containerPort: 3000
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: watcher-github
                  key: github
            - name: CONNECT
              valueFrom:
                secretKeyRef:
                  name: watcher
                  key: connect
