name: Main

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Test
      run: npm test
      env:
        CI: true
  merge:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Merge to update branch
      uses: robotology/gh-action-nightly-merge@4047e51ca91b0629e5c66eb69e0f59ffba33d97b
      with:
        stable_branch: 'main'
        development_branch: 'update'
        allow_ff: true
        user_name: GitHub Action
        user_email: actions@github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
